package com.medilink.store.web;
import com.medilink.store.entity.*; import com.medilink.store.repository.Repositories.*; import com.medilink.store.service.StoreInventoryService; import com.medilink.store.service.StoreLookupService; import com.medilink.store.service.StoreRegistrationService; import jakarta.validation.Valid; import org.springframework.http.MediaType; import org.springframework.security.core.Authentication; import org.springframework.stereotype.Controller; import org.springframework.ui.Model; import org.springframework.validation.BindingResult; import org.springframework.web.bind.annotation.*; import org.springframework.web.multipart.MultipartFile; import java.io.IOException; import java.nio.file.*; import java.util.*;
@Controller public class StoreController {
 private final Users users; private final Stores stores; private final Medicines medicines; private final Inventories inventories; private final Orders orders; private final Customers customers; private final Assignments assignments; private final StoreRegistrationService registration; private final StoreLookupService storeLookup; private final StoreInventoryService storeInventory;
 public StoreController(Users users,Stores stores,Medicines medicines,Inventories inventories,Orders orders,Customers customers,Assignments assignments,StoreRegistrationService registration,StoreLookupService storeLookup,StoreInventoryService storeInventory){this.users=users;this.stores=stores;this.medicines=medicines;this.inventories=inventories;this.orders=orders;this.customers=customers;this.assignments=assignments;this.registration=registration;this.storeLookup=storeLookup;this.storeInventory=storeInventory;}
 private Store currentStore(Authentication auth){
  if(auth==null || !auth.isAuthenticated()) throw new StorePortalException("Please sign in to access the store portal.");
  return storeLookup.findStoreForEmail(auth.getName());
 }
 @GetMapping("/login") String login(){return "login";}
 @GetMapping("/register") String register(Model model){model.addAttribute("form",new StoreRegistrationForm());return "register";}
 @PostMapping("/register") String registerStore(@Valid @ModelAttribute("form") StoreRegistrationForm form,BindingResult errors){if(errors.hasErrors())return "register";try{registration.register(form);return "redirect:/login?registered";}catch(IllegalArgumentException ex){errors.reject("email.exists",ex.getMessage());return "register";}}
 @GetMapping({"/","/dashboard"}) String dashboard(Authentication auth,Model model){Store store=currentStore(auth); List<StoreInventory> stock=inventories.findByStoreId(store.getId()); model.addAttribute("store",store);model.addAttribute("inventoryCount",stock.size());model.addAttribute("lowStock",stock.stream().map(i->medicines.findById(i.getMedicineId()).orElse(null)).filter(Objects::nonNull).filter(m->m.getStockQuantity()<=10).count());model.addAttribute("claimedOrders",assignments.findByStoreId(store.getId()).size());return "dashboard";}
 @GetMapping("/products") String products(Authentication auth,Model model){Store store=currentStore(auth); model.addAttribute("products",storeInventory.listProducts(store.getId()));model.addAttribute("form",new ProductForm());return "products";}
 @PostMapping(value="/products", consumes=MediaType.MULTIPART_FORM_DATA_VALUE) String addProduct(Authentication auth,@Valid @ModelAttribute("form") ProductForm form,BindingResult errors,Model model){if(errors.hasErrors())return products(auth,model); Store store=currentStore(auth); storeInventory.addProduct(store,form,saveImage(form.getImage()));return "redirect:/products?created";}
 @PostMapping(value="/products/{id}", consumes=MediaType.MULTIPART_FORM_DATA_VALUE) String updateProduct(Authentication auth,@PathVariable UUID id,@Valid ProductForm form){Store store=currentStore(auth);storeInventory.updateProduct(store,id,form,saveImage(form.getImage()));return "redirect:/products?updated";}
 @GetMapping("/orders") String orderList(Authentication auth,Model model){Store store=currentStore(auth); Set<UUID> claimed=assignments.findByStoreId(store.getId()).stream().map(StoreOrderAssignment::getOrderId).collect(java.util.stream.Collectors.toSet()); model.addAttribute("orders",orders.findAllByOrderByCreatedAtDesc());model.addAttribute("claimed",claimed);model.addAttribute("customers",users.findAll().stream().collect(java.util.stream.Collectors.toMap(UserAccount::getId,u->u)));model.addAttribute("customerProfiles",customers.findAll().stream().collect(java.util.stream.Collectors.toMap(CustomerProfile::getUserId,c->c)));return "orders";}
 @PostMapping("/orders/{id}/claim") String claim(Authentication auth,@PathVariable UUID id){Store store=currentStore(auth); if(assignments.findByOrderId(id).isEmpty())assignments.save(new StoreOrderAssignment(store.getId(),id));return "redirect:/orders";}
 @PostMapping("/orders/{id}/status") String status(Authentication auth,@PathVariable UUID id,@RequestParam int status){Store store=currentStore(auth); boolean owned=assignments.findByStoreId(store.getId()).stream().anyMatch(a->a.getOrderId().equals(id));if(owned && status>=1 && status<=3){Order order=orders.findById(id).orElseThrow();order.setStatus(status);orders.save(order);}return "redirect:/orders";}
 private String saveImage(MultipartFile image){if(image==null||image.isEmpty())return null; String type=image.getContentType(); if(type==null||!type.startsWith("image/"))throw new IllegalArgumentException("Product image must be an image file."); try{String extension=Optional.ofNullable(image.getOriginalFilename()).filter(n->n.contains(".")).map(n->n.substring(n.lastIndexOf('.'))).orElse(".jpg"); Path folder=Paths.get("uploads").toAbsolutePath().normalize(); Files.createDirectories(folder); String name=UUID.randomUUID()+extension.toLowerCase(Locale.ROOT); image.transferTo(folder.resolve(name)); return "/uploads/"+name;}catch(IOException ex){throw new IllegalStateException("Unable to save the product image.",ex);}}
}
